const assert=require('node:assert/strict');
const p=require('../static/subagent-progress.js');
const a=p.createProjector(),b=p.createProjector();
const event={id:'worker1',status:'queued',task_index:0,task_count:2,summary:'Review project authorization'};
assert.equal(a(event).event,'tool');
assert.equal(a(event),null,'replay does not duplicate worker');
assert.equal(a({...event,status:'running',tool_count:2}).data.args.tool_count,2);
assert.equal(a({...event,status:'queued'}),null,'stale queued cannot regress running');
assert.equal(b(event).event,'tool','different streams have independent state');
const complete=a({...event,status:'completed',duration_seconds:3});
assert.equal(complete.event,'tool_complete');
assert.equal(complete.data.duration,3);
assert.equal(a({...event,status:'running'}),null,'terminal worker never restarts from late SSE');
assert.equal(a({...event,status:'completed'}),null,'terminal replay is idempotent');
const stop=p.createProjector()({...event,status:'cancelled'});
assert.match(p.label(stop.data),/Stopped/);
assert.equal(stop.data.is_error,false,'cancel is not provider failure');
const fail=p.createProjector()({...event,status:'failed'});
assert.equal(fail.data.is_error,true);
assert.match(p.label(fail.data),/Failed/);
assert.equal(p.createProjector()({...event,id:'<script>'}),null);
assert.equal(p.createProjector()({...event,status:'invented'}),null);
assert.equal(p.createProjector()({...event,status:'toString'}),null);
const bounded=p.createProjector()({...event,summary:'x'.repeat(500),reasoning:'PRIVATE',args:{token:'PRIVATE'}});
assert.equal(bounded.data.args.task.length,120);
assert.ok(!JSON.stringify(bounded).includes('PRIVATE'));
console.log('Subagent lifecycle: replay, concurrency, ordering, cancel/error and bounded presentation passed.');

const restored=p.createProjector([{...complete.data,done:true}]);
assert.equal(restored(event),null,'fresh attachment rejects replay older than restored completion');
assert.equal(restored({...event,status:'running'}),null);
const resume=p.createProjector([{name:'subagent_progress',tid:'subagent:worker1',args:{status:'running',tool_count:8}}]);
assert.equal(resume({...event,status:'running',tool_count:2}).data.args.tool_count,8,'late progress cannot lower tool count');
