import fs from 'node:fs';
import path from 'node:path';
import {test,expect,open,session,api,auth} from './fixtures';

test('US-SP-SKILL-LIFECYCLE-CLICKS edit cancel save and delete only the selected disposable skill',async({page})=>{
  const name='qa-click-skill-'+Date.now();
  const original=`---\nname: ${name}\ndescription: Disposable click evidence\n---\nOriginal skill instructions.\n`;
  const saved=original.replace('Original skill instructions.','Updated skill instructions with exact second line.\nSecond line.');
  await open(page,'skills');
  await page.getByRole('button',{name:'New skill',exact:true}).click();
  await page.locator('#skillFormName').fill(name);
  await page.locator('#skillFormContent').fill(original);
  await page.locator('#btnSaveSkillDetail').click();
  await expect(page.locator('#skillDetailTitle')).toHaveText(name);
  const read=()=>api(page,'/api/skills/content?name='+encodeURIComponent(name));
  const created=(await read()).body;
  expect(created.content).toBe(original);
  expect(fs.readFileSync(path.join(created.skill_dir,'SKILL.md'),'utf8')).toBe(original);
  await page.locator('#btnEditSkillDetail').click();
  await expect(page.locator('#skillFormName')).toBeDisabled();
  await page.locator('#skillFormContent').fill('CANCELLED SKILL CHANGE');
  await page.locator('#btnCancelSkillDetail').click();
  await expect(page.locator('#skillDetailBody')).toContainText('Original skill instructions.');
  expect((await read()).body.content).toBe(original);
  await page.locator('#btnEditSkillDetail').click();
  await page.locator('#skillFormContent').fill(saved);
  await page.locator('#btnSaveSkillDetail').click();
  await expect(page.locator('#skillDetailBody')).toContainText('Updated skill instructions');
  expect((await read()).body.content).toBe(saved);
  await page.reload();
  await page.locator('.rail-btn[data-panel="skills"]').click();
  await page.locator('.skill-item').filter({has:page.locator('.skill-name',{hasText:name})}).click();
  await expect(page.locator('#skillDetailBody')).toContainText('Second line.');
  await page.locator('#btnDeleteSkillDetail').click();
  await expect(page.locator('#appDialogCancel')).toBeFocused();
  await page.locator('#appDialogCancel').click();
  expect((await read()).body.content).toBe(saved);
  await page.locator('#btnDeleteSkillDetail').click();
  await page.locator('#appDialogConfirm').click();
  await expect(page.locator('.skill-name').filter({hasText:name})).toHaveCount(0);
  const missing=await read();
  // The existing skill-content API uses an explicit failed result at HTTP 200.
  expect(missing.status).toBe(200);
  expect(missing.body.success).toBe(false);
  expect(missing.body.error).toContain('not found');
  expect(JSON.stringify(missing.body)).not.toContain('Updated skill instructions');
  expect(fs.existsSync(path.join(created.skill_dir,'SKILL.md'))).toBe(false);
  expect((await api(page,'/api/skills/content?name=qa-review')).body.content).toContain('Review synthetic QA evidence');
  await page.reload();
  await page.locator('.rail-btn[data-panel="skills"]').click();
  await expect(page.locator('.skill-name').filter({hasText:name})).toHaveCount(0);
});

test('US-SP-FILE-CHOOSER-CLICKS navigate child upload exact bytes copy relative path and reject denied reader',async({page,context})=>{
  const name='qa-click-upload-'+Date.now()+'.txt';
  const bytes='Uploaded through the visible workspace chooser.\nExact UTF-8: café.\n';
  await context.grantPermissions(['clipboard-read','clipboard-write']);
  await open(page);const sid=await session(page);
  await page.locator('#btnWorkspacePanelToggle').click();
  await page.locator('#fileTree .file-item').filter({hasText:'qa-folder'}).dblclick();
  await expect(page.locator('#breadcrumbBar')).toContainText('qa-folder');
  const chooser=page.waitForEvent('filechooser');
  await page.locator('#btnUploadWorkspace').click();
  const uploaded=page.waitForResponse(r=>r.url().endsWith('/api/workspace/upload')&&r.request().method()==='POST');
  await (await chooser).setFiles({name,mimeType:'text/plain',buffer:Buffer.from(bytes)});
  expect((await uploaded).status()).toBe(200);
  await expect(page.locator('#fileTree')).toContainText(name);
  const target=path.join(auth.workspace,'qa-folder',name);
  expect(fs.readFileSync(target,'utf8')).toBe(bytes);
  expect(fs.existsSync(path.join(auth.workspace,name))).toBe(false);
  const listing=await api(page,'/api/list?session_id='+sid+'&path=qa-folder');
  expect(listing.status).toBe(200);expect(JSON.stringify(listing.body)).toContain(name);
  await page.locator('#fileTree .file-item').filter({hasText:name}).click();
  await expect(page.locator('#previewCode')).toContainText('Exact UTF-8: café.');
  await page.locator('#btnCopyPreviewRelPath').click();
  await expect.poll(()=>page.evaluate(()=>navigator.clipboard.readText())).toBe('qa-folder/'+name);
  await page.locator('#btnClearPreview').click();
  await page.locator('#btnUpDir').click();
  await expect(page.locator('#fileTree')).toContainText('qa-evidence.txt');
  await expect(page.locator('#fileTree')).not.toContainText(name);
  const denied=await page.request.get('/api/file/raw?session_id='+sid+'&path='+encodeURIComponent('qa-folder/'+name),{
    headers:{Cookie:auth.cookie_name+'='+auth.cookies.denied},
  });
  expect([403,404]).toContain(denied.status());
  expect(await denied.text()).not.toContain(bytes);
  expect(fs.readFileSync(target,'utf8')).toBe(bytes);
});

test('US-SP-SESS-IMPORT-CLICKS visible JSON chooser imports exact transcript and malformed JSON creates no session',async({page})=>{
  await open(page);const oldSid=await session(page);
  const title='QA click imported '+Date.now();
  const messages=[{role:'user',content:'QA exact imported user\nSecond line.'},{role:'assistant',content:'QA exact imported assistant.'}];
  await page.locator('.rail-btn[data-panel="settings"]').click();
  await page.locator('[data-settings-section="conversation"]').click();
  const chooser=page.waitForEvent('filechooser');
  await page.locator('#btnImportJSON').click();
  const imported=page.waitForResponse(r=>r.url().endsWith('/api/session/import')&&r.request().method()==='POST');
  await (await chooser).setFiles({name:'qa-import.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({title,messages,workspace:auth.workspace}))});
  const response=await imported;expect(response.status()).toBe(200);
  const importedSid=(await response.json()).session.session_id;expect(importedSid).not.toBe(oldSid);
  await expect(page).toHaveURL(new RegExp('/session/'+importedSid));
  await expect(page.locator('#messages')).toContainText('QA exact imported assistant.');
  const persisted=(await api(page,'/api/session?session_id='+importedSid)).body.session;
  expect(persisted.title).toBe(title);
  expect(persisted.messages.map((m:any)=>({role:m.role,content:m.content}))).toEqual(messages);
  await page.reload();await expect(page.locator('#messages')).toContainText('QA exact imported user');
  await page.locator('.rail-btn[data-panel="settings"]').click();
  await page.locator('[data-settings-section="conversation"]').click();
  const before=(await api(page,'/api/sessions')).body;
  let importRequests=0;
  page.on('request',r=>{if(r.url().endsWith('/api/session/import')&&r.method()==='POST')importRequests++;});
  const invalidChooser=page.waitForEvent('filechooser');await page.locator('#btnImportJSON').click();
  await (await invalidChooser).setFiles({name:'qa-invalid.json',mimeType:'application/json',buffer:Buffer.from('{"messages": INVALID JSON}')});
  await expect(page.locator('#toast.show')).toContainText(/import failed|invalid|unexpected/i);
  expect(importRequests).toBe(0);
  const after=(await api(page,'/api/sessions')).body;
  const ids=(payload:any)=>payload.sessions.map((s:any)=>s.session_id).sort();
  expect(ids(after)).toEqual(ids(before));
  expect((await api(page,'/api/session?session_id='+importedSid)).body.session.messages.map((m:any)=>({role:m.role,content:m.content}))).toEqual(messages);
});

test('US-SP-CHAT-ATTACH-CHOOSER-CLICKS attach opens real chooser and removal leaves draft and disk untouched',async({page})=>{
  await open(page);const sid=await session(page);
  const draft='Unsent draft stays while choosing attachments';
  const name='qa-unsent-chooser-'+Date.now()+'.txt';
  await page.locator('#msg').fill(draft);
  let uploads=0;
  page.on('request',r=>{if(r.url().endsWith('/api/upload')&&r.method()==='POST')uploads++;});
  const chooser=page.waitForEvent('filechooser');
  await page.locator('#btnAttach').click();
  await (await chooser).setFiles({name,mimeType:'text/plain',buffer:Buffer.from('This attachment is deliberately never sent.')});
  await expect(page.locator('#attachTray .attach-chip')).toHaveCount(1);
  await expect(page.locator('#attachTray')).toContainText(name);
  await page.locator('#attachTray .attach-chip').getByRole('button').click();
  await expect(page.locator('#attachTray .attach-chip')).toHaveCount(0);
  await expect(page.locator('#msg')).toHaveValue(draft);
  expect(uploads).toBe(0);
  expect(JSON.stringify((await api(page,'/api/session?session_id='+sid)).body.session.messages)).not.toContain(name);
  expect(fs.existsSync(path.join(auth.workspace,name))).toBe(false);
});
