import fs from 'node:fs';
import path from 'node:path';
import {test,expect,open,session,api,capture} from './fixtures';
async function slow(page:any){await open(page);const sid=await session(page);await page.locator('#msg').fill('QA_SLOW_RESPONSE');await page.locator('#btnSend').click();await expect(page.locator('#btnSend')).toHaveAttribute('aria-label','Stop generation');return sid;}
test('US-SP-CHAT-006 queue follow-up waits then produces two persisted ordered turns',async({page},info)=>{
 const sid=await slow(page);await page.locator('#msg').fill('/queue QA_QUEUED_FOLLOWUP');await page.locator('#btnSend').click();await expect(page.locator('#queueCard')).toContainText('QA_QUEUED_FOLLOWUP');await capture(page,'queued-followup',info);await expect(page.locator('#messages')).toContainText('QA_REPLY: QA_QUEUED_FOLLOWUP',{timeout:30000});const r=await api(page,'/api/session?session_id='+sid);const assistants=r.body.session.messages.filter((m:any)=>m.role==='assistant'&&m.content).map((m:any)=>m.content);expect(assistants.join('\n')).toMatch(/QA_REPLY: QA_SLOW_RESPONSE[\s\S]*QA_REPLY: QA_QUEUED_FOLLOWUP/);await expect(page.locator('#queueCard')).not.toHaveClass(/visible/);await expect(page.locator('#queueChips')).toBeEmpty();
});
test('US-SP-CHAT-009 Stop generation cancels in-flight run and accepts a fresh next turn',async({page},info)=>{
 const sid=await slow(page);await page.locator('#btnSend').click();await expect.poll(async()=>(await api(page,'/health')).body.active_runs,{timeout:30000}).toBe(0);await expect(page.locator('#btnSend')).not.toHaveAttribute('aria-label','Stop generation');const cancelled=await api(page,'/api/session?session_id='+sid);expect(cancelled.body.session.messages.filter((m:any)=>m.role==='assistant').map((m:any)=>m.content).join('')).not.toContain('QA_REPLY: QA_SLOW_RESPONSE');await page.locator('#msg').fill('QA_AFTER_STOP');await page.locator('#btnSend').click();await expect(page.locator('#messages')).toContainText('QA_REPLY: QA_AFTER_STOP',{timeout:30000});await capture(page,'after-stop',info);
});
test('US-SP-CHAT-012 hard reload mid-stream restores the same session and finished response once',async({page})=>{
 const sid=await slow(page);await page.reload();await expect(page).toHaveURL(new RegExp('/session/'+sid));await expect(page.locator('#messages')).toContainText('QA_REPLY: QA_SLOW_RESPONSE',{timeout:30000});const r=await api(page,'/api/session?session_id='+sid);expect(r.body.session.messages.filter((m:any)=>m.role==='assistant'&&String(m.content).includes('QA_REPLY: QA_SLOW_RESPONSE'))).toHaveLength(1);
});
test('US-SP-CHAT-011 persisted unsent draft survives hard reload without creating a turn',async({page})=>{
 await open(page);const sid=await session(page);await page.locator('#msg').fill('QA_UNSENT_DRAFT');await expect.poll(async()=>JSON.stringify((await api(page,'/api/session?session_id='+sid)).body)).toContain('QA_UNSENT_DRAFT');await page.reload();await expect(page.locator('#msg')).toHaveValue('QA_UNSENT_DRAFT');expect((await api(page,'/api/session?session_id='+sid)).body.session.messages).toEqual([]);
});
test('US-SP-CHAT-008 explicit interrupt cancels first response and starts requested next message',async({page})=>{
 const sid=await slow(page);await page.locator('#msg').fill('/interrupt QA_INTERRUPT_FOLLOWUP');await page.locator('#btnSend').click();await expect(page.locator('#messages')).toContainText('QA_REPLY: QA_INTERRUPT_FOLLOWUP',{timeout:30000});const r=await api(page,'/api/session?session_id='+sid);const answers=r.body.session.messages.filter((m:any)=>m.role==='assistant').map((m:any)=>m.content).join('\n');expect(answers).not.toContain('QA_REPLY: QA_SLOW_RESPONSE');expect(answers).toContain('QA_REPLY: QA_INTERRUPT_FOLLOWUP');expect(r.body.session.messages.filter((m:any)=>m.role==='assistant'&&String(m.content).includes('QA_REPLY: QA_INTERRUPT_FOLLOWUP'))).toHaveLength(1);
});
test('US-SP-CHAT-007 actual steer accepted mid-turn influences next model iteration',async({page},info)=>{
 await open(page);await session(page);await page.locator('#msg').fill('QA_STEER_WINDOW');await page.locator('#btnSend').click();await expect(page.locator('#btnSend')).toHaveAttribute('aria-label','Stop generation');const evidence=path.join(path.dirname(path.resolve(process.env.QA_SESSIONS!)),'provider-evidence.jsonl');await expect.poll(()=>fs.existsSync(evidence)?fs.readFileSync(evidence,'utf8'):'').toContain('request_started');await page.locator('#msg').fill('/steer QA_ACTUAL_STEER');const response=page.waitForResponse(r=>r.url().includes('/api/chat/steer')&&r.request().method()==='POST');await page.locator('#btnSend').click();expect((await response).status()).toBe(200);await expect(page.locator('#msg')).toHaveValue('');await expect(page.locator('#messages')).toContainText('QA_REPLY: QA_ACTUAL_STEER',{timeout:30000});await capture(page,'steer-completed',info);
});
