import fs from 'node:fs';
import path from 'node:path';
import {test, expect, open, api, auth} from './fixtures';

test.use({user: 'bob'});

test('US-SP-SESS-IMPORT-AUTHORITY JSON chooser rejects unauthorized workspace before creating a session and allowed import ignores forged identity', async ({page}) => {
  const name = 'qa-import-authority-' + Date.now();
  const directory = path.join(auth.workspace, name);
  fs.mkdirSync(directory);
  const secret = path.join(directory, 'private.txt');
  fs.writeFileSync(secret, 'QA_IMPORT_PRIVATE_CONTENT\n');
  const adminHeaders = {Cookie: auth.cookie_name + '=' + auth.cookies.admin};
  const added = await page.request.post('/api/workspaces/add', {headers: adminHeaders, data: {path: directory, name}});
  expect(added.status()).toBe(200);
  const assigned = await page.request.post('/api/workspaces/assign', {headers: adminHeaders, data: {path: directory, owner_email: 'admin@example.test', members: []}});
  expect(assigned.status()).toBe(200);
  await open(page);
  const before = (await api(page, '/api/sessions')).body.sessions.map((s: any) => s.session_id).sort();
  const adminBefore = await page.request.get('/api/sessions', {headers: adminHeaders});
  expect(adminBefore.status()).toBe(200);
  const beforeAll = (await adminBefore.json()).sessions.map((s: any) => s.session_id).sort();
  expect(JSON.stringify((await api(page, '/api/workspaces')).body)).not.toContain(directory);
  expect((await api(page, '/api/session/new', {workspace: directory})).status).toBe(403);
  const messages = [{role: 'user', content: 'QA exact authorized import\nUTF-8 café.'}, {role: 'assistant', content: 'QA preserved imported answer.'}];
  const forged = {title: name, messages, workspace: directory, owner_email: 'admin@example.test', profile: 'qa-research', participants: ['admin@example.test']};
  await page.locator('.rail-btn[data-panel="settings"]').click();
  await page.locator('[data-settings-section="conversation"]').click();
  const deniedChooser = page.waitForEvent('filechooser');
  await page.locator('#btnImportJSON').click();
  const rejected = page.waitForResponse(r => r.url().endsWith('/api/session/import') && r.request().method() === 'POST');
  await (await deniedChooser).setFiles({name: 'qa-forbidden-import.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(forged))});
  const rejection = await rejected;
  expect(rejection.status()).toBe(403);
  expect(await rejection.text()).not.toContain('QA_IMPORT_PRIVATE_CONTENT');
  await expect(page.locator('#toast.show')).toContainText(/import failed/i);
  expect((await api(page, '/api/sessions')).body.sessions.map((s: any) => s.session_id).sort()).toEqual(before);
  const adminAfter = await page.request.get('/api/sessions', {headers: adminHeaders});
  expect(adminAfter.status()).toBe(200);
  expect((await adminAfter.json()).sessions.map((s: any) => s.session_id).sort()).toEqual(beforeAll);
  expect(fs.readFileSync(secret, 'utf8')).toBe('QA_IMPORT_PRIVATE_CONTENT\n');
  const allowedChooser = page.waitForEvent('filechooser');
  await page.locator('#btnImportJSON').click();
  const imported = page.waitForResponse(r => r.url().endsWith('/api/session/import') && r.request().method() === 'POST');
  await (await allowedChooser).setFiles({name: 'qa-allowed-import.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify({...forged, workspace: auth.workspace}))});
  const response = await imported;
  expect(response.status()).toBe(200);
  const sid = (await response.json()).session.session_id;
  expect(beforeAll).not.toContain(sid);
  await expect(page).toHaveURL(new RegExp('/session/' + sid));
  await expect(page.locator('#messages')).toContainText('QA preserved imported answer.');
  const read = await api(page, '/api/session?session_id=' + sid);
  expect(read.status).toBe(200);
  expect(read.body.session).toMatchObject({title: name, workspace: auth.workspace, owner_email: 'bob@example.test', profile: 'default', participants: []});
  expect(read.body.session.messages.map((m: any) => ({role: m.role, content: m.content}))).toEqual(messages);
  await page.reload();
  await expect(page.locator('#messages')).toContainText('QA exact authorized import');
  expect((await api(page, '/api/session?session_id=' + sid)).body.session.messages.map((m: any) => ({role: m.role, content: m.content}))).toEqual(messages);
  const deniedRead = await api(page, '/api/file?session_id=' + sid + '&path=' + encodeURIComponent(secret));
  expect(deniedRead.status).toBe(403);
  expect(JSON.stringify(deniedRead.body)).not.toContain('QA_IMPORT_PRIVATE_CONTENT');
  expect(fs.readFileSync(secret, 'utf8')).toBe('QA_IMPORT_PRIVATE_CONTENT\n');
});
