import fs from 'node:fs';
import { test, expect, open, session, api, capture } from './fixtures';
async function conversation(page:any){await open(page);const sid=await session(page);await page.locator('#msg').fill('QA_SESSION_LIFECYCLE');await page.locator('#btnSend').click();await expect(page.locator('#messages')).toContainText('QA_REPLY: QA_SESSION_LIFECYCLE',{timeout:30000});return sid;}
async function menu(page:any,sid:string){const row=page.locator('.session-item[data-sid="'+sid+'"]');await row.hover();await row.locator('.session-actions-trigger').click();await expect(page.locator('.session-action-menu')).toBeVisible();}
test('US-SP-SESS-ACTIONS pin duplicate and delete operate on chosen persisted session',async({page},info)=>{
 const sid=await conversation(page);await menu(page,sid);await capture(page,'session-menu',info);await page.getByRole('menuitem',{name:'Pin conversation',exact:true}).click();await expect.poll(async()=>(await api(page,'/api/session?session_id='+sid)).body.session.pinned).toBe(true);
 await menu(page,sid);await page.getByRole('menuitem',{name:'Duplicate conversation',exact:true}).click();await expect.poll(()=>page.url()).not.toContain('/session/'+sid);const copy=page.url().split('/session/')[1];await expect(page.locator('#messages')).toContainText('QA_REPLY: QA_SESSION_LIFECYCLE');
 await menu(page,copy);await page.getByRole('menuitem',{name:'Delete conversation',exact:true}).click();await page.locator('#appDialogConfirm').click();await expect(page.locator('.session-item[data-sid="'+copy+'"]')).toHaveCount(0);expect((await api(page,'/api/session?session_id='+sid)).status).toBe(200);
});
for(const format of ['JSON','HTML','Markdown'])test(`US-SP-SESS-EXPORT-${format} actual download includes persisted transcript`,async({page})=>{
 const sid=await conversation(page);await page.locator('.rail-btn[data-panel="settings"]').click();const locator=format==='JSON'?'#btnExportJSON':format==='HTML'?'#btnExportHTML':'#btnDownload';const downloadPromise=page.waitForEvent('download');await page.locator(locator).click();const download=await downloadPromise;const filepath=await download.path();expect(filepath).toBeTruthy();const bytes=fs.readFileSync(filepath!,'utf8');expect(bytes).toContain('QA_SESSION_LIFECYCLE');expect(bytes).toContain('QA_REPLY');
});
test('US-SP-SESS-CLEAR clear cancel preserves messages and confirm clears persisted transcript',async({page})=>{
 const sid=await conversation(page);await expect.poll(async()=>(await api(page,'/health')).body.active_runs).toBe(0);await page.locator('.rail-btn[data-panel="settings"]').click();await page.locator('#btnClearConvModal').click();await page.locator('#appDialogCancel').click();expect((await api(page,'/api/session?session_id='+sid)).body.session.messages.length).toBeGreaterThan(0);
 await page.locator('#btnClearConvModal').click();await page.locator('#appDialogConfirm').click();await expect.poll(async()=>(await api(page,'/api/session?session_id='+sid)).body.session.messages).toEqual([]);await page.locator('.rail-btn[data-panel="chat"]').click();await page.locator('#msg').fill('QA_AFTER_CLEAR');await page.locator('#btnSend').click();await expect(page.locator('#messages')).toContainText('QA_REPLY: QA_AFTER_CLEAR',{timeout:30000});await expect(page.locator('#messages')).not.toContainText('QA_SESSION_LIFECYCLE');await page.reload();await expect(page.locator('#messages')).toContainText('QA_REPLY: QA_AFTER_CLEAR');await expect(page.locator('#messages')).not.toContainText('QA_SESSION_LIFECYCLE');
});
test('US-SP-UX-MOBILE drawer and chat mode remain reachable at 390px',async({page},info)=>{
 await page.setViewportSize({width:390,height:844});await page.goto('/');await expect(page.locator('#btnHamburger')).toBeVisible();await page.locator('#btnHamburger').click();await expect(page.locator('.sidebar')).toBeVisible();await page.locator('.sidebar [data-panel="profiles"]').click();await expect(page.locator('#panelProfiles')).toBeVisible();await page.locator('.sidebar [data-panel="chat"]').click();await expect(page.locator('.sidebar')).not.toHaveClass(/mobile-open/);await expect(page.locator('#chatModeHeader')).toBeVisible();await page.locator('#chatModeNormal').click();await expect(page.locator('#chatModeNormal')).toHaveAttribute('aria-pressed','true');await capture(page,'mobile-chat',info);
});
