import fs from 'node:fs';import path from 'node:path';
import {test,expect,open,api,auth,capture,session} from './fixtures';
import type {Page,Browser} from '@playwright/test';
declare const S:any;
async function actor(browser:Browser,user="bob"){const context=await browser.newContext({baseURL:auth.base_url});await context.route('**/*',r=>['127.0.0.1','localhost','[::1]'].includes(new URL(r.request().url()).hostname)?r.continue():r.abort('blockedbyclient'));await context.addCookies([{name:auth.cookie_name,value:auth.cookies[user],url:auth.base_url,httpOnly:true,sameSite:'Lax'}]);const page=await context.newPage();const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await expect(page.locator('#msg')).toBeVisible();return{context,page,errors};}
async function create(page:Page,label:string){const name='qa-ws-'+label+'-'+Date.now(),directory=path.join(auth.workspace,name);fs.mkdirSync(directory);fs.writeFileSync(path.join(directory,'membership.txt'),'QA_PRIVATE_MEMBERSHIP_'+label);await open(page,'workspaces');await page.getByRole('button',{name:'Add space',exact:true}).click();await page.locator('#workspaceFormPath').fill(directory);await page.locator('#workspaceFormName').fill(name);await page.locator('#btnSaveWorkspaceDetail').click();await expect(page.locator('#workspaceDetailTitle')).toContainText(name);return{name,directory};}
async function tab(page:Page){await open(page,'governance');await page.locator('[data-gov-tab="workspaces"]').click();}
const row=(page:Page,directory:string)=>page.locator('#govPaneWorkspaces tbody tr').filter({has:page.getByText(directory,{exact:true})});
async function read(page:Page,directory:string){const r=await api(page,'/api/workspaces');expect(r.status).toBe(200);return r.body.workspaces.find((w:any)=>w.path===directory);}
async function assign(page:Page,directory:string,owner:string,members:string){await tab(page);const r=row(page,directory);await r.locator('[id^="govWsOwner_"]').fill(owner);await r.locator('[id^="govWsMembers_"]').fill(members);const pending=page.waitForResponse(r=>r.url().endsWith('/api/workspaces/assign')&&r.request().method()==='POST');await r.getByRole('button',{name:'Save',exact:true}).click();expect((await pending).status()).toBe(200);}
async function lens(page:Page,email:string){await page.locator('#govWsUserFilter').fill(email);await page.locator('[onclick="_govApplyWsUserFilter()"]').click();}
async function grantName(page:Page,name:string){await open(page,'governance');await page.locator('[data-gov-tab="users"]').click();const before=(await api(page,'/api/governance/users')).body.users['bob@example.test'];await page.locator('#govPaneUsers tr').filter({hasText:'bob@example.test'}).getByRole('button',{name:'Edit',exact:true}).click();await page.locator('details.gov-access-details').nth(0).locator('summary').click();await page.locator('#govUserGrantWorkspacesInput').fill(name);await page.locator('#govUserGrantWorkspacesInput').press('Enter');await page.locator('#govUserGrantWorkspacesInput').press('Escape');const pending=page.waitForResponse(r=>r.url().endsWith('/api/governance/users/update'));await page.locator('#govUserSave').click();expect((await pending).status()).toBe(200);return before;}
async function restore(page:Page,entry:any){const current=(await api(page,'/api/governance/users')).body;const status=await page.evaluate(async({entry,etag})=>{const r=await fetch('/api/governance/users/update',{method:'POST',headers:{'Content-Type':'application/json','If-Match':etag},body:JSON.stringify({email:'bob@example.test',entry})});return r.status;},{entry,etag:current.etag});expect(status).toBe(200);}

test('US-SP-WS-OWNERSHIP owner member fields normalize persist and per-user lens add remove clear preserves ownership',async({page,browser},info)=>{
 const w=await create(page,'fields');const member=await actor(browser);
 try{
  await assign(page,w.directory,'ALICE@example.test','BOB@example.test, bob@example.test');expect(await read(page,w.directory)).toMatchObject({owner_email:'alice@example.test',members:['bob@example.test']});await page.reload();await tab(page);await expect(row(page,w.directory).locator('[id^="govWsOwner_"]')).toHaveValue('alice@example.test');await expect(row(page,w.directory).locator('[id^="govWsMembers_"]')).toHaveValue('bob@example.test');
  await lens(page,'alice@example.test');await expect(row(page,w.directory).getByText('Owner',{exact:true})).toBeVisible();await lens(page,'bob@example.test');await expect(row(page,w.directory).getByText('Member',{exact:true})).toBeVisible();
  const removed=page.waitForResponse(r=>r.url().endsWith('/api/workspaces/assign'));await row(page,w.directory).getByRole('button',{name:'Remove bob@example.test',exact:true}).click();expect((await removed).status()).toBe(200);await expect(row(page,w.directory).getByText('No access',{exact:true})).toBeVisible();expect(await read(page,w.directory)).toMatchObject({owner_email:'alice@example.test'});expect((await read(page,w.directory)).members||[]).toEqual([]);
  const added=page.waitForResponse(r=>r.url().endsWith('/api/workspaces/assign'));await row(page,w.directory).getByRole('button',{name:'Add bob@example.test',exact:true}).click();expect((await added).status()).toBe(200);expect((await read(page,w.directory)).members).toEqual(['bob@example.test']);
  await page.locator('[onclick="_govClearWsUserFilter()"]').click();await expect(page.locator('#govWsUserFilter')).toHaveValue('');await expect(row(page,w.directory).getByRole('button',{name:'Remove bob@example.test',exact:true})).toHaveCount(0);
  const before=await read(page,w.directory);expect((await api(member.page,'/api/workspaces/assign',{path:w.directory,owner_email:'bob@example.test',members:[]})).status).toBe(403);expect(await read(page,w.directory)).toEqual(before);await capture(page,'workspace-assignment-controls',info);
 }finally{expect((await api(page,'/api/workspaces/remove',{path:w.directory})).status).toBe(200);await member.context.close();expect(member.errors).toEqual([]);}
});

test('US-SP-WS-REVOKE removing workspace membership blocks retained session file reads and fresh activation despite role ceiling',async({page,browser},info)=>{
 const w=await create(page,'revoke');const original=await grantName(page,w.name);await assign(page,w.directory,'admin@example.test','bob@example.test');const member=await actor(browser);
 try{
  expect(await read(member.page,w.directory)).toMatchObject({name:w.name});const sid=await session(member.page);await member.page.locator('#composerWorkspaceChip').click();const switched=member.page.waitForResponse(r=>new URL(r.url()).pathname==='/api/session/update'&&r.request().method()==='POST');await member.page.locator('#composerWsDropdown .ws-opt').filter({has:member.page.getByText(w.name,{exact:true})}).click();expect((await switched).status()).toBe(200);expect((await api(member.page,'/api/session?session_id='+sid)).body.session.workspace).toBe(w.directory);
  await member.page.locator('.rail-btn[data-panel="chat"]').click();await member.page.locator('#btnWorkspacePanelToggle').click();await member.page.locator('#fileTree .file-item').filter({hasText:'membership.txt'}).click();await expect(member.page.locator('#previewCode')).toContainText('QA_PRIVATE_MEMBERSHIP_revoke');
  await tab(page);await lens(page,'bob@example.test');const revoked=page.waitForResponse(r=>r.url().endsWith('/api/workspaces/assign'));await row(page,w.directory).getByRole('button',{name:'Remove bob@example.test',exact:true}).click();expect((await revoked).status()).toBe(200);expect((await read(page,w.directory)).members||[]).toEqual([]);
  const file=await api(member.page,'/api/file?session_id='+sid+'&path=membership.txt');expect.soft(file.status,'revoked retained-session file read').toBe(403);
  expect((await api(member.page,'/api/session/update',{session_id:sid,workspace:w.directory})).status).toBe(403);expect((await api(member.page,'/api/workspaces')).body.last).not.toBe(w.directory);
  expect((await api(member.page,'/api/terminal/start',{session_id:sid})).status).toBe(403);
  await member.page.locator('#composerWorkspaceChip').click();await expect(member.page.locator('#composerWsDropdown .ws-opt').filter({has:member.page.getByText(w.name,{exact:true})})).toHaveCount(0);await member.page.locator('#composerWorkspaceChip').click();
  expect.soft(await read(member.page,w.directory),'revoked workspace disappears from catalog').toBeUndefined();
  expect.soft((await api(member.page,'/api/session/new',{workspace:w.directory,worktree:false})).status,'revoked fresh session activation').toBe(403);
  expect((await api(member.page,'/api/workspaces/rename',{path:w.directory,name:'FORBIDDEN'})).status).toBe(403);expect((await read(page,w.directory)).name).toBe(w.name);await capture(member.page,'retained-workspace-after-revoke',info);
 }finally{await restore(page,original);expect((await api(page,'/api/workspaces/remove',{path:w.directory})).status).toBe(200);await member.context.close();expect(member.errors).toEqual([]);}
});

test('US-SP-WS-FOREIGN named policy ceiling cannot expose or activate an owned workspace without membership',async({page,browser},info)=>{
 const w=await create(page,'foreign');const original=await grantName(page,w.name);const member=await actor(browser);
 try{
  expect((await read(page,w.directory)).owner_email).toBe('admin@example.test');expect.soft(await read(member.page,w.directory),'foreign owned workspace catalog privacy').toBeUndefined();
  const created=await api(member.page,'/api/session/new',{workspace:w.directory,worktree:false});expect.soft(created.status,'foreign workspace direct activation').toBe(403);
  for(const [url,data] of [['/api/workspaces/rename',{path:w.directory,name:'FORBIDDEN'}],['/api/workspaces/remove',{path:w.directory}],['/api/workspaces/assign',{path:w.directory,members:['bob@example.test']}]] as const)expect((await api(member.page,url,data)).status,url).toBe(403);
  expect((await read(page,w.directory)).name).toBe(w.name);expect(fs.readFileSync(path.join(w.directory,'membership.txt'),'utf8')).toBe('QA_PRIVATE_MEMBERSHIP_foreign');await capture(member.page,'foreign-workspace-boundaries',info);
 }finally{await restore(page,original);expect((await api(page,'/api/workspaces/remove',{path:w.directory})).status).toBe(200);await member.context.close();expect(member.errors).toEqual([]);}
});


test('US-SP-WS-RUNTIME revoking workspace member while real write awaits approval blocks engine effect after Allow once',async({page,browser},info)=>{
 const w=await create(page,'runtime');await assign(page,w.directory,'admin@example.test','manualapprove@example.test');const member=await actor(browser,'manualapprove');const target=path.join(w.directory,'parked-write.txt');
 try{
  const created=await api(member.page,'/api/session/new',{workspace:w.directory,worktree:false});expect(created.status).toBe(200);const sid=created.body.session.session_id;await member.page.goto('/session/'+sid);await expect(member.page.locator('#msg')).toBeVisible();
  await member.page.locator('#msg').fill('QA_GOV_WRITE|'+target);await member.page.locator('#btnSend').click();await expect(member.page.locator('#approvalCard')).toBeVisible({timeout:25000});expect(fs.existsSync(target)).toBe(false);await capture(member.page,'workspace-write-parked-before-revoke',info);
  await assign(page,w.directory,'admin@example.test','');expect((await read(page,w.directory)).members||[]).toEqual([]);
  await member.page.locator('#approvalBtnOnce').click();await expect(member.page.locator('#messages')).toContainText('workspace_access_revoked',{timeout:35000});expect(fs.existsSync(target)).toBe(false);await expect(member.page.locator('#approvalCard')).toBeHidden();
  const saved=await api(member.page,'/api/session?session_id='+sid);expect(saved.status).toBe(200);expect(saved.body.session.messages.some((m:any)=>m.role==='tool'&&m.content.includes('Action blocked by governance: workspace_access_revoked'))).toBe(true);expect((await api(member.page,'/api/file?session_id='+sid+'&path=membership.txt')).status).toBe(403);
  await expect.poll(async()=>(await api(member.page,'/api/session/status?session_id='+sid)).body.agent_running).toBe(false);
  const failed=async()=>{const summary=member.page.locator('.tool-call-group-summary');await expect(summary).toHaveCount(1);if(await summary.getAttribute('aria-expanded')==='false')await summary.click();const card=member.page.locator('.tool-card-row[data-tool-name="write_file"]');await expect(card).toBeVisible();await info.attach('workspace-denied-card-diagnostics',{body:JSON.stringify(await member.page.evaluate(()=>({messages:S.messages.map((m:any)=>({role:m.role,partial:m._partial_tool_calls,toolResult:m.role==='tool'?m.content:undefined,scene:m._anchor_activity_scene?.activity_rows?.filter((r:any)=>r.role==='tool')})),card:{...((document.querySelector('.tool-card-row[data-tool-name="write_file"]') as HTMLElement)?.dataset||{})}}))),contentType:'application/json'});await expect(card).toHaveAttribute('data-tool-error','true');await expect(card.locator('.tool-card-name-label')).toHaveText(/^Failed/);await expect(member.page.locator('#messages').getByText(/^(Updated|Updating) (parked-write.txt|a file)$/)).toHaveCount(0);};await failed();await member.page.reload();await expect(member.page.locator('#msg')).toBeVisible();await failed();expect(fs.existsSync(target)).toBe(false);await capture(member.page,'workspace-write-denied-after-revoke',info);
 }finally{expect((await api(page,'/api/workspaces/remove',{path:w.directory})).status).toBe(200);await member.context.close();expect(member.errors).toEqual([]);}
});
